# Generated by Django 6.0.2 on 2026-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
