# Generated by Django 6.0.2 on 2026-10-01 22:48

import unicodedata

import django.utils.timezone
from django.db import migrations, models


def normalize_search_text(value):
    """Copie de places.models.normalize_search_text : une migration ne dépend pas du code qui évolue"""
    decomposed = unicodedata.normalize('NFKD', value or '')
    without_accents = ''.join(char for char in decomposed if not unicodedata.combining(char))
    folded = without_accents.casefold().replace('œ', 'oe').replace('æ', 'ae')
    return ' '.join(folded.split())


def fill_search_text(apps, schema_editor):
    """
    Remplit search_text pour les lieux existants (les nouveaux le reçoivent à l'enregistrement).
    Même format que Place.build_search_text : les modèles des migrations n'ont pas ses méthodes.
    """
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all().only('id', 'name', 'city', 'address', 'description'):
        place.search_text = ' | '.join(
            normalize_search_text(part) for part in (place.name, place.city, place.address, place.description)
        )
        place.save(update_fields=['search_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_account_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='search_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(fill_search_text, migrations.RunPython.noop),
    ]
