services:
  - type: web
    name: spotfinder-api
    env: python
    plan: free
    buildCommand: ". venv/bin/activate && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn spotfinderapi.wsgi:application"
    numInstances: 1
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: "3.11"
