"""
Django settings for spotfinderapi project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================
# SÉCURITÉ - Variables d'environnement OBLIGATOIRES
# ============================================

def get_secret(key, default=None):
    """
    Récupère une variable d'environnement obligatoire.
    En développement : utilise la valeur par défaut si fournie.
    En production : lève une exception si non définie.
    """
    value = config(key, default=default)
    
    # En production (DEBUG=False), aucune valeur par défaut n'est acceptée
    if not config('DEBUG', default=False, cast=bool):
        if value == default or value is None:
            raise ImproperlyConfigured(
                f'La variable d\'environnement {key} est obligatoire en production. '
                f'Définissez-la dans votre environnement ou fichier .env'
            )
    
    return value


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret('SECRET_KEY', default='django-insecure-dev-key-change-in-production-123456789')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Liste des hôtes autorisés - OBLIGATOIRE en production
ALLOWED_HOSTS = get_secret('ALLOWED_HOSTS', default='localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS.split(',') if host.strip()]

# Validation supplémentaire pour ALLOWED_HOSTS en production
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS ne peut pas être vide en production. '
        'Définissez la variable d\'environnement ALLOWED_HOSTS'
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'cloudinary_storage',
    'cloudinary',
    'corsheaders',
    'places',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spotfinderapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spotfinderapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuration PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='spotfinder_db'),
        'USER': config('DB_USER', default='spotfinder_user'),
        'PASSWORD': config('DB_PASSWORD', default='password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Alternative : Configuration via DATABASE_URL (recommandé pour production)
# DATABASE_URL = config('DATABASE_URL', default='postgresql://user:password@localhost:5432/dbname')
# Utilisez dj-database-url pour parser DATABASE_URL si nécessaire


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = config('STATIC_URL', default='static/')
STATIC_ROOT = config('STATIC_ROOT', default=BASE_DIR / 'staticfiles')

# Media files configuration
if config('USE_CLOUDINARY', default=False, cast=bool):
    # Configuration Cloudinary pour le stockage en production
    import cloudinary_storage
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': config('CLOUDINARY_API_KEY'),
        'API_SECRET': config('CLOUDINARY_API_SECRET'),
    }
    CLOUDINARY_URL = config('CLOUDINARY_URL')
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_URL = config('MEDIA_URL', default='https://res.cloudinary.com/')
else:
    # Stockage local pour le développement
    MEDIA_URL = config('MEDIA_URL', default='media/')
    MEDIA_ROOT = config('MEDIA_ROOT', default=BASE_DIR / 'media')

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Swagger/OpenAPI Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': config('API_TITLE', default='SpotFinder API'),
    'DESCRIPTION': config('API_DESCRIPTION', default='API REST pour SpotFinder - Trouvez et partagez vos lieux préférés'),
    'VERSION': config('API_VERSION', default='1.0.0'),
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'CONTACT': {
        'name': config('API_CONTACT_NAME', default='SpotFinder Support'),
        'email': config('API_CONTACT_EMAIL', default='support@spotfinder.com'),
    },
    'LICENSE': {
        'name': config('API_LICENSE_NAME', default='MIT License'),
    },
}

# ============================================
# CORS - Cross-Origin Resource Sharing
# ============================================
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:8000',
    cast=lambda x: [origin.strip() for origin in x.split(',')]
)

CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', default=True, cast=bool)

# ============================================
# SÉCURITÉ - PRODUCTION
# ============================================

# En production (DEBUG=False), appliquer les paramètres de sécurité stricts
if not DEBUG:
    # HTTPS
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    
    # HSTS
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    
    # Headers de sécurité
    SECURE_REFERRER_POLICY = config('SECURE_REFERRER_POLICY', default='strict-origin-when-cross-origin')
    X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='DENY')

# ============================================
# WHITENOISE - Serveur fichiers statiques
# ============================================
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Optimisation Whitenoise
WHITENOISE_AUTOREFRESH = config('WHITENOISE_AUTOREFRESH', default=DEBUG, cast=bool)
